# fly.toml app configuration file generated for ancient-wind-8519 on 2023-07-21T18:37:21+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ancient-wind-8519"
primary_region = "lhr"

[[mounts]]
  source = "data"
  destination = "/data"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
